#!/usr/bin/env bash
# PreToolUse hook: block edits/writes to generated or local-state files that
# should never be hand-edited (build output, SQLite db files & journals).
#
# Exit 2 => the tool call is blocked and the message goes back to Claude.
set -euo pipefail

input="$(cat)"

file_path="$(printf '%s' "$input" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("tool_input",{}).get("file_path",""))' 2>/dev/null || true)"

[ -z "$file_path" ] && exit 0

case "$file_path" in
  */target/*|target/*)
    echo "Refusing to edit build output under target/ — it is regenerated by Maven." >&2
    exit 2 ;;
  *.db|*.db-journal|*.db-wal|*.db-shm|*.sqlite|*.sqlite3)
    echo "Refusing to edit a SQLite database file ($file_path) — change schema via a Flyway migration / JPA entity instead." >&2
    exit 2 ;;
esac

exit 0
