package com.company.pos.menu.api;

public enum MenuChangeType {
    GROUP_CREATED, GROUP_UPDATED, GROUP_DEACTIVATED, GROUP_REACTIVATED,
    OPTION_ADDED, OPTION_UPDATED, OPTION_DEACTIVATED, OPTION_REACTIVATED,
    GROUP_ASSIGNED, GROUP_UNASSIGNED
}
